package com.sky.text.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sky.text.FriendBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "table_user".
*/
public class FriendBeanDao extends AbstractDao<FriendBean, Long> {

    public static final String TABLENAME = "table_user";

    /**
     * Properties of entity FriendBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IcoUrl = new Property(1, String.class, "icoUrl", false, "ICO_URL");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Signature = new Property(3, String.class, "signature", false, "SIGNATURE");
        public final static Property Rating = new Property(4, float.class, "rating", false, "RATING");
    }


    public FriendBeanDao(DaoConfig config) {
        super(config);
    }
    
    public FriendBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"table_user\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ICO_URL\" TEXT," + // 1: icoUrl
                "\"NAME\" TEXT," + // 2: name
                "\"SIGNATURE\" TEXT," + // 3: signature
                "\"RATING\" REAL NOT NULL );"); // 4: rating
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"table_user\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FriendBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String icoUrl = entity.getIcoUrl();
        if (icoUrl != null) {
            stmt.bindString(2, icoUrl);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String signature = entity.getSignature();
        if (signature != null) {
            stmt.bindString(4, signature);
        }
        stmt.bindDouble(5, entity.getRating());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FriendBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String icoUrl = entity.getIcoUrl();
        if (icoUrl != null) {
            stmt.bindString(2, icoUrl);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String signature = entity.getSignature();
        if (signature != null) {
            stmt.bindString(4, signature);
        }
        stmt.bindDouble(5, entity.getRating());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FriendBean readEntity(Cursor cursor, int offset) {
        FriendBean entity = new FriendBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // icoUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // signature
            cursor.getFloat(offset + 4) // rating
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FriendBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIcoUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSignature(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRating(cursor.getFloat(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FriendBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FriendBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FriendBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
